// B-916: the per-INVOCATION leg-cost record's shared-core accessors.
//
// A conduction shows what it cost. The unit of record is ONE `claude` INVOCATION, not one leg: a
// single leg runs 1..8 invocations (container/provision.sh's `_b772_run` loop — the B-718 resume
// attempt, its cold fallback, and up to 7 B-772 model-switch iterations), each of which may be on a
// DIFFERENT model and therefore has its own usage, its own cost and its own duration. Rows are
// grouped back into one leg by the WORKER-GENERATED `leg_key`; the web sums them per leg and per
// conduction. Persisted in `public.conduction_leg_costs` (harmony-web's B-916 migration).
//
// THE AGENT-NEUTRALITY SEAM (load-bearing — read src/daemon/scheduler.ts's SchedulerDeps.runCommand
// guardrail comment before touching this file). No scheduling, classification, retry or park
// decision has ever read, or may ever read, a single byte of what the worker wrote: the exit code is
// still the ONLY control signal out of a worker. Everything here is CAPTURE FOR DISPLAY, on the
// worker's own side of the seam — the claude-specific JSON parse lives in
// src/tools/claude-result-parse.ts and is reached from the worker profile (container/provision.sh)
// through the `harmony leg-cost record` CLI accessor, exactly as B-772 reaches
// `harmony model read-handoff`. src/daemon/ is untouched by this feature, by construction.
//
// These are IN-PROCESS shared-core functions, following src/tools/conduction-record.ts's convention
// exactly: deliberately NOT registered as MCP tools, exported through the src/tools barrel only, and
// consumed by the CLI accessor (src/cli/commands/leg-cost.ts) as a plain function call over an
// authenticated Supabase client.
//
// NEVER THROWS (B-846 tolerance) — the same discipline, for the same reason, as scheduler.ts's
// `flushWorkerOutput`: harmony-web's migration creating `conduction_leg_costs` merges and promotes
// on its OWN schedule, so between this plugin merging and that promotion every write here is
// rejected by PostgREST with a table-absent error. A cost record is a diagnostic nicety; it must
// never be able to fail a leg, before or after the migration lands. Every failure — a missing table,
// an RLS refusal, a network blip, an absent HARMONY_CONDUCTION_ID — is logged to stderr and dropped.

import type { SupabaseClient } from '@supabase/supabase-js';

/** Which figure the stored `total_cost_usd` actually IS, so the UI can say so rather than implying a
 *  precision it does not have. `'cli'` — the CLI's own `total_cost_usd`, authoritative; `'derived'`
 *  — computed here from the token counts and the published price table (see
 *  src/tools/claude-result-parse.ts); `'unknown'` — neither was available, and `total_cost_usd` is
 *  null. */
export type LegCostSource = 'cli' | 'derived' | 'unknown';

/** One row of `public.conduction_leg_costs` — ONE claude invocation. Column-for-column the shape
 *  harmony-web's B-916 migration creates; keep the two in step. */
export interface LegCostRecord {
  id: string;
  conduction_id: string;
  task_id: string | null;
  /** Groups the invocations of ONE leg. Generated by the worker (container/provision.sh) once per
   *  leg, before its first invocation — never derived here, because only the worker knows where one
   *  leg's invocations start and stop. */
  leg_key: string;
  /** The gate that was running when this invocation started — stamped BEFORE the invocation, never
   *  resolved at write time: by the time an invocation returns, the gate it just did the work of has
   *  already advanced, so a write-time read would mis-name which activity spent the money. */
  gate: string | null;
  model: string | null;
  invocation_index: number;
  input_tokens: number | null;
  output_tokens: number | null;
  cache_read_input_tokens: number | null;
  /** The CLI's own `usage.cache_creation_input_tokens` TOTAL. The two bucket columns below are the
   *  separately-reported 1h/5m split of it (`usage.cache_creation`) — they are priced separately
   *  (different rates) and are NOT redundant with this total. */
  cache_creation_input_tokens: number | null;
  cache_creation_1h_input_tokens: number | null;
  cache_creation_5m_input_tokens: number | null;
  thinking_tokens: number | null;
  total_cost_usd: number | null;
  cost_source: LegCostSource;
  num_turns: number | null;
  duration_ms: number | null;
  duration_api_ms: number | null;
  session_id: string | null;
  is_error: boolean;
  service_tier: string | null;
  created_at: string;
}

const LEG_COST_COLS =
  'id, conduction_id, task_id, leg_key, gate, model, invocation_index, ' +
  'input_tokens, output_tokens, cache_read_input_tokens, cache_creation_input_tokens, ' +
  'cache_creation_1h_input_tokens, cache_creation_5m_input_tokens, thinking_tokens, ' +
  'total_cost_usd, cost_source, num_turns, duration_ms, duration_api_ms, ' +
  'session_id, is_error, service_tier, created_at';

/** Everything `recordLegCost` needs. `conduction_id` and `leg_key` are the only required fields —
 *  every measurement is optional, because a capture that read a malformed/absent result envelope
 *  must still record THAT the invocation happened rather than nothing at all. */
export interface RecordLegCostArgs {
  conduction_id: string;
  leg_key: string;
  /** Resolved here from the conduction when the caller does not already know it. */
  task_id?: string | null;
  gate?: string | null;
  model?: string | null;
  /** Omitted -> derived as "however many invocations this leg has already recorded" (see
   *  resolveInvocationIndex below). The worker normally supplies it, since it is the one that knows
   *  the true ordering including the resume-attempt/cold-fallback pair. */
  invocation_index?: number | null;
  input_tokens?: number | null;
  output_tokens?: number | null;
  cache_read_input_tokens?: number | null;
  cache_creation_input_tokens?: number | null;
  cache_creation_1h_input_tokens?: number | null;
  cache_creation_5m_input_tokens?: number | null;
  thinking_tokens?: number | null;
  total_cost_usd?: number | null;
  cost_source?: LegCostSource;
  num_turns?: number | null;
  duration_ms?: number | null;
  duration_api_ms?: number | null;
  session_id?: string | null;
  is_error?: boolean;
  service_tier?: string | null;
}

/** One WARNING line, stderr only — this module's single failure channel. Mirrors
 *  src/config/run-config.ts's `fetchModelCatalog` convention: name the cause AND say plainly that
 *  the pre-migration shape is expected, so nobody debugs a non-bug. Never stdout: the CLI accessor
 *  around this runs inside a worker whose stdout is a captured operator tail. */
function warn(message: string): void {
  console.error(`harmony leg-cost: WARNING — ${message}`);
}

const errText = (err: unknown): string =>
  (err as { message?: string })?.message ?? String(err);

/** The conduction context a leg-cost write/gate-stamp needs, read in ONE query: the owning task's
 *  id (the row's `task_id`) plus its workflow position (what `resolveGatePhase` projects onto a
 *  gate). Embedded via the `conductions.task_id -> tasks.id` FK, the same PostgREST embedding idiom
 *  `listConductions` uses for `tasks(priority)`.
 *
 *  Never throws: returns null for an absent conduction id, an unreadable row, or any error at all —
 *  every consumer degrades to "no context", which costs a null `task_id`/`gate`, never a leg. */
export async function resolveLegCostContext(
  client: SupabaseClient | null | undefined,
  conductionId: string | null | undefined,
): Promise<{ task_id: string | null; workflow_state: string | null; workflow_activity: string | null } | null> {
  if (!client || !conductionId) return null;
  try {
    const { data, error } = await client
      .from('conductions')
      .select('task_id, tasks(workflow_state, workflow_activity)')
      .eq('id', conductionId)
      .maybeSingle();
    if (error) {
      warn(`could not read conduction ${conductionId} for leg-cost context (${errText(error)})`);
      return null;
    }
    if (!data) return null;
    const row = data as unknown as {
      task_id?: string | null;
      tasks?: { workflow_state?: string | null; workflow_activity?: string | null } | null;
    };
    return {
      task_id: row.task_id ?? null,
      workflow_state: row.tasks?.workflow_state ?? null,
      workflow_activity: row.tasks?.workflow_activity ?? null,
    };
  } catch (err: unknown) {
    warn(`reading conduction ${conductionId} for leg-cost context threw (${errText(err)})`);
    return null;
  }
}

/** How many invocations this leg has already recorded — the default `invocation_index` when the
 *  caller does not supply one. A plain count, deliberately NOT a serial: two concurrent writers for
 *  ONE leg_key cannot exist (a leg's invocations are strictly sequential — provision.sh waits on
 *  each PID before starting the next), so there is no race to guard against. Degrades to 0 on any
 *  read failure, which is honest for a first row and harmless for a later one: ordering is a
 *  display nicety, `created_at` is the real sequence. */
async function resolveInvocationIndex(
  client: SupabaseClient,
  conductionId: string,
  legKey: string,
): Promise<number> {
  try {
    const { count, error } = await client
      .from('conduction_leg_costs')
      .select('id', { count: 'exact', head: true })
      .eq('conduction_id', conductionId)
      .eq('leg_key', legKey);
    if (error) return 0;
    return count ?? 0;
  } catch {
    return 0;
  }
}

/** Insert ONE invocation's cost row. Returns whether the row actually landed.
 *
 *  NEVER THROWS — see the module header. A missing `conduction_id` (no HARMONY_CONDUCTION_ID in the
 *  worker's env: a manual/dogfood container run rather than a conducted leg) is a SKIP, not a
 *  failure: there is no conduction for the row to belong to, so there is nothing to record and
 *  nothing has gone wrong. Every other failure — the table not existing yet (the expected
 *  pre-migration shape), an RLS refusal, a network blip — logs one WARNING and returns false. */
export async function recordLegCost(
  client: SupabaseClient | null | undefined,
  args: RecordLegCostArgs,
): Promise<boolean> {
  if (!client) return false;
  if (!args.conduction_id) return false;
  if (!args.leg_key) return false;

  try {
    const invocationIndex =
      args.invocation_index ??
      (await resolveInvocationIndex(client, args.conduction_id, args.leg_key));

    const row: Record<string, unknown> = {
      conduction_id: args.conduction_id,
      task_id: args.task_id ?? null,
      leg_key: args.leg_key,
      gate: args.gate ?? null,
      model: args.model ?? null,
      invocation_index: invocationIndex,
      input_tokens: args.input_tokens ?? null,
      output_tokens: args.output_tokens ?? null,
      cache_read_input_tokens: args.cache_read_input_tokens ?? null,
      cache_creation_input_tokens: args.cache_creation_input_tokens ?? null,
      cache_creation_1h_input_tokens: args.cache_creation_1h_input_tokens ?? null,
      cache_creation_5m_input_tokens: args.cache_creation_5m_input_tokens ?? null,
      thinking_tokens: args.thinking_tokens ?? null,
      total_cost_usd: args.total_cost_usd ?? null,
      cost_source: args.cost_source ?? 'unknown',
      num_turns: args.num_turns ?? null,
      duration_ms: args.duration_ms ?? null,
      duration_api_ms: args.duration_api_ms ?? null,
      session_id: args.session_id ?? null,
      is_error: args.is_error ?? false,
      service_tier: args.service_tier ?? null,
    };

    const { error } = await client.from('conduction_leg_costs').insert(row);
    if (error) {
      warn(
        `the leg-cost row was not written (${errText(error)}). This is the EXPECTED shape while ` +
          "harmony-web's conduction_leg_costs migration has not yet landed on this environment's " +
          'Supabase project (B-383 prod-before-promote) — the leg itself is unaffected.',
      );
      return false;
    }
    return true;
  } catch (err: unknown) {
    warn(`writing the leg-cost row threw (${errText(err)}) — the leg itself is unaffected`);
    return false;
  }
}

/** Read back one conduction's invocation rows, oldest first — optionally narrowed to ONE leg.
 *  Ordered by `created_at` then `invocation_index`, so a caller can group by `leg_key` and sum in
 *  the order the invocations actually ran. Never throws: returns `[]` on any failure (including the
 *  table not existing yet), for the same reason the write swallows. */
export async function listLegCosts(
  client: SupabaseClient | null | undefined,
  args: { conduction_id: string; leg_key?: string },
): Promise<LegCostRecord[]> {
  if (!client || !args.conduction_id) return [];
  try {
    let query = client
      .from('conduction_leg_costs')
      .select(LEG_COST_COLS)
      .eq('conduction_id', args.conduction_id);
    if (args.leg_key) query = query.eq('leg_key', args.leg_key);
    const { data, error } = await query
      .order('created_at', { ascending: true })
      .order('invocation_index', { ascending: true });
    if (error) {
      warn(`could not read leg costs for conduction ${args.conduction_id} (${errText(error)})`);
      return [];
    }
    return (data as unknown as LegCostRecord[]) ?? [];
  } catch (err: unknown) {
    warn(`reading leg costs for conduction ${args.conduction_id} threw (${errText(err)})`);
    return [];
  }
}
